export enum IPCEvents {
  PRESENTATION_START = "PRESENTATION:start",
  PRESENTATION_INIT = "PRESENTATION:init",
  PRESENTATION_NEXT_SLIDE = "PRESENTATION:next",
  PRESENTATION_PREV_SLIDE = "PRESENTATION:previous",

  MAIN_NEXT_SLIDE = "MAIN:next",
  MAIN_PREV_SLIDE = "MAIN:previous",
}
